# =============================================================================
# DEV CONFIG - Local development entry point (Waveshare 7" S3 panel)
# =============================================================================
# Flash with: esphome run dev.yaml
# =============================================================================

substitutions:
  cover_art_placeholder_file: "../../common/assets/cover_art_placeholder.svg"
  name: "espcontrol-waveshare-s3"
  friendly_name: "EspControl Waveshare 7inch"
  espcontrol_component_url: "../.."
  mdi_font_file: "../../common/assets/fonts/materialdesignicons-webfont-7.4.47.ttf"
  espcontrol_component_ref: "HEAD"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  espcontrol: !include packages.yaml

web_server:
  js_url: ""
  js_include: "../../docs/public/webserver/www.js"
